version: '3'
services:

    #backend
    nodeserver:
        build: ./server
        container_name: speller-app
        ports: 
            - 3030:3000
    
    #frontend
    vuejs:
        build: ./client
        container_name: speller-ui
        ports: 
            - 8080:80